### ISSUE TITLE
ERROR: sql: database is closed

### ISSUE THREAD

**Issue by yanjf90** [gatechain/node-binary#1]
macos 下 gatecli con-account create 命令创建共识账户 提示 ERROR: sql: database is closed

**Comment by mofeixiaobao** [comment]
> macos 下 gatecli con-account create 命令创建共识账户 提示 ERROR: sql: database is closed

未能重现问题，请提供运行环境说明，及更多报错信息。

**Comment by yanjf90** [comment]
操作系统：10.14.6 (18G103) 
版本：1.0.0.4

 gatecli status -n http://localhost:8080
{"lastHeight":"122839","lastConsensusVersion":"v4","nextConsensusVersion":"v4","nextConsensusVersionRound":"122840","nextConsensusVersionSupported":true,"timeSinceLastRound":"12","catchupTime":"0","hasSyncedSinceStartup":false,"step":"2","period":"0","zeroTimeStamp":"2020-08-10T13:51:44.489915Z","deadline":"43","fastRecoveryDeadline":"349","minimumTxFee":"10000000","minimumBlockTxFee":"10"}

gatecli con-account create gt11mkr2zrpfp3ecd0xjx8w294wzcgy54vgqgsxfa6cyammwd9whnhltx3thsyh606qv9ye0rv
ERROR: sql: database is closed
就这一句 报错信息，没其他提示了
node.log 无报错信息

**Comment by yanjf90** [comment]
普通账户地址 是我钱包上生成的，余额有1.1GT

**Comment by yanjf90** [comment]
bons-macbook:~ yanjf$ ls -al | grep gate
drwxr-xr-x    4 yanjf  staff        128  8  8 22:14 .gatecli
drwxr-xr-x   14 yanjf  staff        448  8 10 21:43 .gated

**Comment by mofeixiaobao** [comment]
临时办法:可以将config中RootDir指定到.gated目录(绝对路径)，另外目前钱包的账户是不支持参与共识的，可以本地通过gatecli创建账户，再用钱包账户打钱过来。后续我们会针对本issue更新版本

**Comment by yanjf90** [comment]
增加RootDir配置后，创建成功了
