### ISSUE TITLE
有人搭成功吗   我怎么感觉糊弄人呢

### ISSUE THREAD

**Issue by kfzxjm** [gatechain/node-binary#2]
/usr/local/bin/gated: line 1: version: command not found
/usr/local/bin/gated: line 2: oid: command not found
size: '55096680': No such file

**Comment by mofeixiaobao** [comment]
您好！可以搭建成功的，有很多用户成功搭建。您的问题是可能未完全下载完成，请确认二进制文件gated是否完全下载成功，如本地执行命令行操作“usr/local/bin/gated version --long”。另外请详细描述问题及操作步骤以便定位原因，谢谢。

**Comment by kfzxjm** [comment]
可以了

**Comment by kfzxjm** [comment]
可以了 谢谢
